stages:
  download:
    cmd: python3 -m mlops_greenlight.dataset
    deps:
      - mlops_greenlight/dataset.py
    outs:
      - data/raw           

  convert:
    cmd: python3 -m mlops_greenlight.convert
    deps:
      - data/raw
      - mlops_greenlight/convert.py
    outs:
      - data/processed

  train:
    cmd: python3 -m mlops_greenlight.modeling.train
    deps:
      - mlops_greenlight/modeling/train.py
      - data/processed/
      - data/raw
    outs:
      - models/
  test:
    cmd: python3 -m mlops_greenlight.modeling.test
    deps:
      - mlops_greenlight/modeling/test.py
      - models/
  encoding:
    cmd: bash mlops_greenlight/predictions2mp4.sh ./models/predictions/ ./models/predictions/output.mp4
    deps:
      - mlops_greenlight/predictions2mp4.sh
      - models/predictions/
    
